apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends-deploy
  namespace: { { .Values.namespace.name } }

spec:
  replicas: { { .Values.namespace.name } }
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - image: { .Values.image.repository }
          tag: { .Values.image.tag }
          imagePullPolicy: { .Values.image.pullPolicy }
          name: { .Values.image.repository }
          ports:
            - containerPort: { .Values.containerPort }
              protocol: TCP
          resources:
            requests:
              cpu: { .Values.resources.requests.cpu }
              memory: { .Values.resources.requests.memory }
            limits:
              cpu: { .Values.resources.limits.cpu }
              memory: { .Values.resources.limits.memory }
          livenessProbe:
            httpGet:
              path: { .Values.livenessProbe.path }
              port: { .Values.containerPort }
          readinessProbe:
            httpGet:
              path: { .Values.readinessProbe.path }
              port: { .Values.containerPort }
