apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  destination:
    namespace: techtrends
    server: https://kubernetes.default.svc
  project: techtrends
  source:
    helm:
      valueFiles:
        - values-staging.yaml
    path: helm
    repoURL: https://github.com/Tarunshrma/techtrend
    targetRevision: HEAD
