namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protcol: TCP
  type: ClusterIP

image:
  repository: tarunshrma/techtrends
  tag: 0.0.4
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 3111

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz
